version: '3.8'
services:
  # Node Server
  node-server: # container name (like --name)
    build: . # dockerfile path
    ports: # port mapping
      - 3000:3000 # host:container port mapping
    working_dir: /app # working directory
    env_file: # env file
      - .env # .env file path
    restart: unless-stopped # restart policy
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/global_wireless_test
      - NODE_ENV=development
      - PORT=3000

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: global_wireless_test
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: global_wireless_test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: global_wireless_test_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql 

volumes:
  mysql_data: